version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: credit-bot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: credit_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - credit_bot_postgres_data:/var/lib/postgresql/data

volumes:
  credit_bot_postgres_data: