spring:
  profiles:
    active: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/credit_bot
    username: 
    password: 
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

telegram:
  bot:
    username: credit_olga_telegram_bot
    token: ${TELEGRAM_BOT_TOKEN}

  manager-password: ${TELEGRAM_MANAGER_PASSWORD}
  manager-ids: ${TELEGRAM_MANAGER_IDS}
